### ISSUE TITLE
Inconsistent behavior with byCountry

### ISSUE THREAD

**Issue by Helium314** [westnordost/osmfeatures#19]
When searching
```
featureDictionary
    .byTerm("lush")
    .forGeometry(geometryType)
    .inCountry(country)
    .forLocale(*locales)
    .find()
```
for point geometry, US english locale, in Austria, I get feature with id `shop/cosmetics/lush-a08666`.
But when I try to find it by id
```
featureDictionary
    .byId("shop/cosmetics/lush-a08666")
    .forLocale(*locales)
    .inCountry(country)
    .get()
```
nothing is found, unless I remove the `inCountry(country)`.

This seems rather inconsistent, especially considering `.inCountry("DE") // also include things (brands) that only exist in Germany` in the readme, which implies that `inCountry` may find more, but not fewer features.

I'm not really sure, but this seems like a bug, or at least unclear description in the readme.

**Comment by westnordost** [comment]
Sounds like a bug to me. The code that handles the country code parameter is here:

https://github.com/westnordost/osmfeatures/blob/master/library/src/main/java/de/westnordost/osmfeatures/FeatureDictionary.java#L90

**Comment by westnordost** [comment]
Hm, are you sure? I don't seem to be able to reproduce it with this test:

https://github.com/westnordost/osmfeatures/blob/bcc5754981a84677ebaa007553b2a8ef17d025f0/library/src/test/java/de/westnordost/osmfeatures/FeatureDictionaryTest.java#L708-L737

**Comment by westnordost** [comment]
Hold on, now I can reproduce it.

**Comment by Helium314** [comment]
To add some details:
I noticed this issue in SCEE, which saves some sort of _recently used features_ list, where sometimes recently used brands are missing. Features added to the list are all found using the `SearchFeaturesDialog`, which uses the query in first post.

After some testing right now, I think in `byId`, `inCountry(country)` actually uses the `presets-<country>.json`, instead of using both `presets.json` _and_ `presets-<country>.json` as per description ("also include things (brands) that only exist in Germany").

**Comment by westnordost** [comment]
Actually, scrap my last comment. I cannot reproduce it after all.

So maybe the issue is not with the dictionary but with the parser?

**Comment by westnordost** [comment]
Okay, got it

**Comment by Helium314** [comment]
Great, thanks!

**Comment by westnordost** [comment]
Though, you probably won't actually want brand features to appear in that "recently used features" list because it is very unlikely that a shop of the same brand will be more or less next to each other.

Are you sure that this is a feature that would make sense though? Does the presence of a particular kind of shop increase the likeliness of the exact same kind of shop in the vicinity? Maybe for common things like restaurants and cafés which tend to be clustered in neighbourhoods where people tend to go out to have dinner or something, but then again restaurants and cafés are already in the shortcut list.
For malls etc. it may be a slight help as sometimes the shops are kind of themed on different floors, e.g. eateries are on level X, clothes shops are on level Y. However, shops in malls more often than not belong to some chain, so the interface should not really encourage to tag everything as a clothes shop but instead check if there is a NSI preset for that.

But actually, I realize now that SCEE allows to add any kind of POI, so for that it looks like it very much makes sense (e.g. if one wants to map all the street lanterns or something).
